# Generated by Django 5.1 on 2024-09-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0004_alter_brand_parent_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
