# Generated by Django 5.1 on 2024-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0006_product_brand_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
