# Generated by Django 4.2 on 2025-06-08 18:51

import apps.lib.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[apps.lib.validators.valid_phone_number], verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=48, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=48, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('created_time', models.TimeField(verbose_name=True)),
                ('expire_time', models.TimeField(default=60)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
