# Generated by Django 4.2 on 2025-06-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
        migrations.DeleteModel(
            name='Sms',
        ),
    ]
