# Generated by Django 4.2 on 2025-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[('Charge', 'Charge'), ('Purchase', 'Purchase'), ('Transfer received', 'Transfer received'), ('Transfer Sent', 'Transfer Sent')]),
        ),
    ]
