# Generated by Django 4.2 on 2025-03-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Charge', 'Charge'), ('Purchase', 'Purchase'), ('Transfer received', 'Transfer received'), ('Transfer Sent', 'Transfer Sent')], max_length=152),
        ),
    ]
