# Generated by Django 4.2 on 2024-11-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstock',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='partnerstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='catalogue.product'),
        ),
    ]
